[package]
name = "storm_derive"
edition = "2018"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11"
either = "1"
proc-macro2 = "1"
quote = "1"
serde = "1"
syn = "1"
toml = "0.5"

[dev-dependencies]
